### ISSUE TITLE
Running vizdoom container in kubernetes

### ISSUE THREAD

**Issue by nehaljwani** [mwydmuch/ViZDoom#329]
I was able to get ViZDoom running inside containers in a single pod inside kubernetes and talk to each other. However, I had to specifically enable tty for all the containers. Something like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: vizdoom-host-agent-connection
  labels:
    app: vizdoom-xxxx
spec:
  containers:
  - name: host
    tty: true <-----------------------------------------
    image: xxxxdocker/vizdoom:host
    command:
      - /home/xxxx/run.sh
  - name: randomagent
    tty: true <-----------------------------------------
    image: xxxxdocker/vizdoom:random
    command:
      - /home/xxxx/run.sh
```

It will be great if the documentation is updated with this info. If tty is absent, the vizdoom processes listen for incoming connections on the UDP ports, but none actually send the request or respond to a request.
